### config/routes.yaml
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix:
        fr: /fr
        en: /en

default_route:
    path: /
    controller: App\Controller\ProductController::home

